apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agrosolutions

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - rabbitmq.yaml
  - identity-api.yaml
  - property-api.yaml
  - dataingestion-api.yaml
  - alert-worker.yaml
  - gateway.yaml
  - ingress.yaml
