apiVersion: v1
kind: Secret
metadata:
  name: agrosolutions-secrets
  namespace: agrosolutions
type: Opaque
stringData:
  MongoDB__ConnectionString: "mongodb://mongodb:27017/agrosolutions"
  RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672"
  JwtSettings__Secret: "AgroSolutionsSecretKey2024SuperSecure!"
